/* ========================================================
   FILE: js/data-usrah.js
   TAHUN AJARAN: 2026/2027
   FUNGSI: Menyimpan database awal/default kelompok Usrah.
   CATATAN: Seluruh kelompok lama telah diganti menjadi Usrah 1–8.
   ======================================================== */

const dataAwalUsrahBawaan = {
  "Usrah 1": [
    "ARYA DIFA ALSYA",
    "K.A. M. ABDULLAH SHIDDIQ AGTSALI",
    "MUHAMMAD ABIL IRWANSYAH",
    "HAFIDZ ALRIZKY",
    "HAFIDZ AL ROZI",
    "REZFY FAKHRYAZKA",
    "SYAHRUL RAMADHAN",
    "WAFII FADHLURROHMAN",
    "CAHYIS ISZAM",
    "MUHAMMAD FAISAL FIKRIANSYAH",
    "RAFA",
    "RAFI RAMADHAN",
    "MUHAMMAD ALLAM NUR HUSHAIN",
    "MUHAMMAD FADHIL BUANA"
  ],

  "Usrah 2": [
    "AKBAR PRAYOGA",
    "GHOZY FATHURRAHMAN",
    "BASRI AL HAZIQ ZULFAHMI",
    "ALIF MUHAMMAD YUSUF",
    "ALVIN HERFIANTINO",
    "FAUZAN IBNI JABAR",
    "NIZAM KABISAT",
    "QHEIZAN ALQIZA ARISDA",
    "WAHYU REYDINATA",
    "AQIELA MARSYAH",
    "FADIL NURHALIM",
    "MUHAMMAD SYAKIR HUTABARAT",
    "MUHAMMAD YASIR AL FAZAR JHIRA"
  ],

  "Usrah 3": [
    "ANDES AFENDRA",
    "AHMAD RIYADI",
    "RENAL MARTIN",
    "AHMAD MAULANA",
    "ROID AFDAL",
    "ILHAM",
    "MAHESA AULIA GIFFARI",
    "MUHAMMAD USAMAH",
    "MIKO VAJAR",
    "MUHAMMAD IZAM SAPUTRA",
    "DARREN ATHAYA",
    "REYNALDI MALIK IBRAHIM ALFARIDZI",
    "AIRLANGGA AZKA ABQORI"
  ],

  "Usrah 4": [
    "PRAWIRO PUJO TUNGGAL JATI",
    "ALIF SAMUDRA",
    "NAJMIHADI SYAUQII TAMAAM",
    "MUHAMMAD RIJALUL KAMIL",
    "ADITYA PUTRA IBRAHIM",
    "MUHAMMAD ZIYAD ZHAZHA",
    "BRILLY HANDRIAN",
    "EZA FEBRI AL FADZRI",
    "ABDULLAH MUKTI HAFIDZALLAH",
    "REYFAS RAMADHAN",
    "MUHAMMAD FIRAAS AL - INSYIROH",
    "AHMAD FARHAAN",
    "FAHRY AKBAR RAMDHANI"
  ],

  "Usrah 5": [
    "ANGGA PRATAMA PUTRA",
    "MUHAMMAD RAID MAHRUS",
    "MUHAMMAD FAQIH HAFIDZALLAH",
    "MUHAMAD YUSUF ARROSIYD",
    "ZULFAQIH HAERUNNASIHIN",
    "DAFFA AL MUSYARI",
    "IHZA TRINANDI",
    "NAUFAL AKBAR ALKHATIRI",
    "DZIKRI MUDHOFFAR",
    "ELLENO QUTHBIE HERMAWAN",
    "HADINATA SAPUTRA",
    "MUHAMMAD ALMISKY PRATAMA",
    "MUHAMMAD AQIL RIDHO"
  ],

  "Usrah 6": [
    "DANANG PRASDITYA SANTOSO",
    "MUHAMMAD AL FALAH",
    "ALEXY PRATAMA HADRIAN",
    "AMIN SUGIONO",
    "FATIR AL MUQMINUN HAKIM",
    "MUHAMMAD RAFFI",
    "ILHAM MAULANA",
    "MEDIKA PRATAMA",
    "MUHAMMAD BILAL ARIFI",
    "RIFKI AHNAF",
    "MUHAMMAD AFIF AL BAIHAQI",
    "MUHAMMAD NABIL IRWANSYAH",
    "M. UMAR HALIM RAHMAPUTRA",
    "RIKI WARDANI",
    "RIKO WARDANA",
    "QENZO GAVRIEL ALIFIANDRA"
  ],

  "Usrah 7": [
    "JESSICA PUTRY AYRA",
    "NAMI RIA RAMADHANI",
    "NAJIHA SHAFIYAH AFIFAH",
    "NAURA ADELIA FITRI",
    "QIARA ANJANI DIVANTI",
    "NAYYA SALSABILLA",
    "NAEVA MARNIA",
    "ANISYA SEPTIANI",
    "AISYAH NURUL AULIA",
    "AISYAH NUR KHALIFAH",
    "ADIBA AILA KHANZA",
    "QONITA AZZAHRAH ALFANSYURI"
  ],

  "Usrah 8": [
    "NYAYU MARLITSA ARDHANI",
    "NABILA NUR WAMAWADDA AL- MAIRA",
    "INAYAH NOURAH ANINDYA",
    "FITRAH KIRANA",
    "DINA RUHAYAH",
    "DAFIA NAFLA SYAKIRA",
    "WINDY WINDARI",
    "WILDA",
    "QELZA RAMADHANI ATH THAHIRA",
    "GRINNETA NALANI PUTRI",
    "GHENIS ANDIENTIAZ",
    "EARLYTA ARSYFA SALSABILA",
    "ASHIFA FITRI RAMADHONI"
  ]
};
export const dataAwalUsrah = window.CAHAYA_MASTER_DATA?.usrah || dataAwalUsrahBawaan;
