import test from 'node:test';import assert from 'node:assert/strict';import {applyCaseOperation as apply,routeCounselorCase} from '../assets/js/counselor-model.js';
const session={activeRole:'konselor',user:{uid:'a'},profile:{counselorLevel:'PEMULA'}};
const record={studentId:'s',status:'ditangani',assignedCounselorUid:'a'};
const op=(type,id,data)=>({type,id,data});
test('counselor classification routes serious, moral and three-day repetition to Madya',()=>{assert.equal(routeCounselorCase({severity:'berat'}).level,'MADYA');assert.equal(routeCounselorCase({category:'Etika'}).level,'MADYA');const rows=['01','02','03'].map(d=>({studentId:'s',category:'ALFA',date:`2026-10-${d}`}));assert.equal(routeCounselorCase(rows[2],rows).reason,'THREE_CONSECUTIVE_DAYS');assert.equal(routeCounselorCase(rows[1],rows).level,'PEMULA');});
test('case stages and ownership protected; final points repeat cannot duplicate',()=>{assert.throws(()=>apply(record,op('session','x',{date:'2026-10-04',clarification:'Fakta',caseStatus:'selesai'}),session,1),/Tahap/);let r=record;for(const [i,status]of ['tabayyun','konseling','konsekuensi'].entries())r=apply(r,op('session',`s${i}`,{date:'2026-10-04',clarification:'Fakta',caseStatus:status}),session,i);const p=op('points','final_case',{points:-25,description:'Ringan'});r=apply(r,p,session,4);assert.equal(r.finalPoints,-25);assert.deepEqual(apply(r,p,session,5),r);assert.throws(()=>apply(r,op('points','another',{points:-25,description:'Ringan'}),session,5),/sudah/);assert.throws(()=>apply(r,p,{...session,user:{uid:'b'}},6),/lain/);assert.throws(()=>apply(r,op('session','closed',{date:'2026-10-04',clarification:'Fakta',caseStatus:'selesai'}),session,7),/evaluasi/);});
test('Pemula transfers to Madya; leadership responds only requested escalation and retains counselor ownership',()=>{let r=apply(record,op('escalation','e1',{targetLevel:'konselor_madya',summary:'Perlu Madya'}),session,1);assert.equal(r.assignedCounselorUid,null);const madya={...session,user:{uid:'m'},profile:{counselorLevel:'MADYA'}};r={...r,assignedCounselorUid:'m'};r=apply(r,op('escalation','e2',{targetLevel:'director',summary:'Kebutuhan keputusan',decisionNeeded:'Arahan'}),madya,2);const decision=op('response','resp',{decision:'Disetujui',instruction:'Lanjutkan pendampingan'});assert.throws(()=>apply(r,decision,{...session,activeRole:'deputy_director'},3),/permintaan/);r=apply(r,decision,{...session,activeRole:'director',user:{uid:'d'}},3);assert.equal(r.assignedCounselorUid,'m');assert.equal(r.status,'ditangani');assert.equal(r.higherEscalation.response.actorUid,'d');});

test('Tabayyun records evidence and routes newly discovered serious cases to Madya',()=>{const d={date:'2026-10-04',studentStatement:'Pernyataan',facts:'Fakta',conclusion:'TERBUKTI',discoveredSeverity:'BERAT'};const r=apply(record,op('tabayyun','t',d),session,1);assert.equal(r.status,'eskalasi_diperlukan');assert.equal(r.tabayyunHistory.t.facts,'Fakta');assert.throws(()=>apply(r,op('session','s',{date:d.date,clarification:'Sesi',caseStatus:'konseling'}),session,2),/eskalasi/);const closed=apply(record,op('tabayyun','t2',{...d,conclusion:'TIDAK TERBUKTI'}),session,2);assert.equal(closed.status,'tidak_terbukti');assert.equal(closed.finalPoints,undefined);});
