import test from 'node:test';import assert from 'node:assert/strict';
import {applyHealthOperation as apply,validateJournal} from '../assets/js/health-model.js';import {TASK_GROUPS} from '../assets/js/health-rubric.js';
const stock={name:'Obat Uji',category:'Uji',form:'Tablet',unit:'tablet',batch:'batch1',expiry:'2027-01-01',date:'2026-10-04',storageUnit:'PUTRA',location:'Lemari',storageCondition:'Sesuai label',quantity:5,minimum:1,packagingChecked:true,expiryChecked:true};
const exam={studentId:'s1',date:'2026-10-04',time:'08:00',complaint:'Keluhan uji',learningStatus:'TIDAK_MENGIKUTI',excuseStart:'2026-10-04T08:00',excuseEnd:'2026-10-04T12:00',restLocation:'UKS',disposition:'Dirujuk ke Fasilitas Kesehatan',storageUnit:'PUTRA',medicines:[{stockId:'a',quantity:2,instructions:'Sesuai petugas uji'}]};
const initial=()=>apply(null,{id:'stock',type:'stock',stockId:'a',data:stock},'uks',1);
test('UKS exam and stock debit commit together and retry does not double debit',()=>{const old=initial(),op={id:'exam',type:'exam',data:exam},n=apply(old,op,'uks',2);assert.equal(n.stock.a.quantity,3);assert.equal(old.stock.a.quantity,5);assert.ok(n.records.s1.exam);assert.deepEqual(apply(n,op,'uks',3),n);assert.ok(n.learning_memos.s1.exam.excusedFromLearning);assert.equal(n.learning_memos.s1.exam.complaint,undefined);});
test('UKS insufficient stock, expired batches, wrong unit and duplicate drug rows cannot overspend',()=>{for(const medicines of [[{stockId:'a',quantity:6,instructions:'Uji'}],[{stockId:'a',quantity:3,instructions:'Uji'},{stockId:'a',quantity:3,instructions:'Uji'}]])assert.throws(()=>apply(initial(),{id:'x',type:'exam',data:{...exam,medicines}},'uks',2),/Stok/);assert.throws(()=>apply(initial(),{id:'x',type:'exam',data:{...exam,storageUnit:'PUTRI'}},'uks',2),/unit/);assert.throws(()=>apply(initial(),{id:'x',type:'exam',data:{...exam,date:'2027-02-01'}},'uks',2),/kedaluwarsa/);});
test('daily checklist requires every status, exception reasons and at least one applicable item',()=>{const entries=Object.fromEntries(TASK_GROUPS.flatMap(g=>g.tasks).map(t=>[t.id,{status:'terlaksana',note:''}]));validateJournal(entries);assert.throws(()=>validateJournal({}));entries['KS-01'].status='sebagian';assert.throws(()=>validateJournal(entries),/Alasan/);for(const r of Object.values(entries)){r.status='tidak_berlaku';r.note='Alasan';}assert.throws(()=>validateJournal(entries),/Semua/);});
test('medical referral sends once and decision preserves history',()=>{let n=apply(initial(),{id:'exam',type:'exam',data:exam},'uks',2);n=apply(n,{id:'permit',type:'permit',studentId:'s1',examId:'exam'},'uks',3);assert.equal(n.permits.exam.status,'MENUNGGU_PIMPINAN');n=apply(n,{id:'dec',type:'permit-decision',examId:'exam',data:{status:'DISETUJUI',note:'Dampingi santri'}},'director',4);assert.equal(n.permits.exam.history.length,2);assert.throws(()=>apply(n,{id:'dec2',type:'permit-decision',examId:'exam',data:{status:'DITOLAK',note:'stale'}},'director',5));});

test('UKS corrects only Alfa and preserves original evidence and scores',async()=>{const {correctAttendanceFromHealth,healthMemoActive}=await import('../assets/js/health-model.js');const memo={date:'2026-10-04',excusedFromLearning:true,start:'2026-10-04T08:00',end:'2026-10-04T12:00'};const old={studentId:'s1',status:'Alfa',statusAwal:'Belum Hadir',score:80,points:-40},next=correctAttendanceFromHealth(old,memo,'exam','uks',1);assert.equal(next.status,'Sakit');assert.equal(next.points,0);assert.equal(next.score,80);assert.equal(next.originalStatus,'Alfa');assert.equal(old.status,'Alfa');assert.deepEqual(correctAttendanceFromHealth(next,memo,'exam','uks',2),next);assert.equal(correctAttendanceFromHealth({...old,status:'Hadir'},memo,'exam','uks',1).status,'Hadir');assert.equal(healthMemoActive(memo,'2026-10-04','11:00'),true);assert.equal(healthMemoActive(memo,'2026-10-04','12:00'),false);});
