import {applyHealthOperation} from '../assets/js/health-model.js';
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {webcrypto} from 'node:crypto';
const require=createRequire(import.meta.url),{JSDOM}=require(process.env.MADANI_JSDOM_MODULE||'jsdom'),base=new URL('../',import.meta.url),dom=new JSDOM('<main id="content"></main>',{url:'http://localhost/app/index.html'}),win=dom.window;
let db={},writes=[],failAfterCommit=false;const read=p=>p.split('/').reduce((v,k)=>v?.[k],db)||null;const put=(p,v)=>{const parts=p.split('/');let o=db;for(const k of parts.slice(0,-1))o=o[k]??={};o[parts.at(-1)]=v;writes.push(p);};
const repository={commitHealthOperation:async(y,op,actor)=>{const next=applyHealthOperation(read(`health/${y}`),op,actor,Date.now());put(`health/${y}`,next);if(failAfterCommit){failAfterCommit=false;throw Error('Respons jaringan terputus setelah tersimpan');}return next;},getNode:async p=>read(p),listNode:async p=>Object.entries(read(p)||{}).map(([id,r])=>({id,...r})),saveTeacherSession:async(p,r,o)=>{if((read(p)?.version||0)!==o.expectedVersion)throw Error('Data berubah');put(p,r);return r;}};
const context=vm.createContext({console,document:win.document,window:win,FormData:win.FormData,Intl,Date,URL,crypto:webcrypto,setTimeout,clearTimeout});const exports=Object.keys(repository),mock=new vm.SyntheticModule(exports,function(){for(const k of exports)this.setExport(k,repository[k]);},{context}),cache=new Map();async function load(url){if(url.endsWith('/repository.js'))return mock;if(cache.has(url))return cache.get(url);const m=new vm.SourceTextModule(readFileSync(fileURLToPath(url),'utf8'),{context,identifier:url});cache.set(url,m);await m.link((s,p)=>load(new URL(s,p.identifier).href));return m;}
const mod=await load(new URL('assets/js/health.js',base).href);await mod.evaluate();const H=mod.namespace,ctx={root:win.document.querySelector('main'),yearId:'year',session:{activeRole:'kesehatan',roles:['kesehatan'],user:{uid:'uks'},profile:{name:'Petugas UKS'}},master:{students:[{id:'s1',name:'Santri Satu',gender:'L'}],classes:[],classAssignments:{}},navigate:()=>{}};
const $=s=>ctx.root.querySelector(s);async function flush(){for(let i=0;i<70;i++)await Promise.resolve();}async function click(s){$(s).click();await flush();}function fill(values){for(const[k,v]of Object.entries(values))$(`[name="${k}"]`).value=v;}
test('UKS records examination, teacher memo, stock debit, referral and leader decision end to end',async()=>{
 db={};writes=[];await H.renderHealthStock(ctx);fill({date:'2026-10-01',name:'Obat Uji',category:'Uji',form:'Tablet',unit:'tablet',batch:'A',expiry:'2027-01-01',quantity:5,minimum:1,location:'Lemari',storageCondition:'Sesuai label'});for(const k of ['packagingChecked','expiryChecked'])$(`[name=${k}]`).checked=true;await click('#saveStock');assert.equal(Object.values(read('health/year/stock'))[0].quantity,5);
 await H.renderHealthExamination(ctx);if(process.env.MADANI_VISUAL_QA){mkdirSync('outputs/qa',{recursive:true});writeFileSync('outputs/qa/health-mobile.html','<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UKS — data uji</title>'+['app','portal','teacher','mentoring','health','brand-theme'].map(n=>`<link rel="stylesheet" href="/assets/css/${n}.css?v=39">`).join('')+'<body style="margin:auto;max-width:390px;padding:12px">'+ctx.root.innerHTML+'</body>');}fill({studentId:'s1',date:'2026-10-01',time:'08:00',complaint:'Keluhan uji',learningStatus:'TIDAK_MENGIKUTI',excuseStart:'2026-10-01T08:00',excuseEnd:'2026-10-01T12:00',restLocation:'UKS',disposition:'Dirujuk ke Fasilitas Kesehatan',referralDestination:'Fasilitas kesehatan',companion:'Petugas'});await click('#addMedicine');fill({stockId:Object.keys(read('health/year/stock'))[0],quantity:2,instructions:'Diisi petugas'});await click('#saveExam');assert.equal(Object.values(read('health/year/stock'))[0].quantity,3);assert.equal(Object.keys(read('health/year/records/s1')).length,1);assert.equal(Object.values(read('health/year/learning_memos/s1'))[0].complaint,undefined);
 await H.renderHealthPermits(ctx);await click('[data-submit]');const id=Object.keys(read('health/year/permits'))[0];assert.equal(read('health/year/permits')[id].status,'MENUNGGU_PIMPINAN');await H.renderHealthPermits({...ctx,session:{...ctx.session,activeRole:'director'}});fill({['note-'+id]:'Dampingi santri'});await click('[data-decision]');assert.equal(read('health/year/permits')[id].status,'DISETUJUI');
});
test('non UKS roles cannot open clinical forms',async()=>{await assert.rejects(()=>H.renderHealthExamination({...ctx,session:{...ctx.session,activeRole:'guru_mapel'}}),/khusus/);});

test('retry after an ambiguous stock response keeps the operation identity',async()=>{db={};await H.renderHealthStock(ctx);fill({date:'2026-10-01',name:'Obat Uji',category:'Uji',form:'Tablet',unit:'tablet',batch:'A',expiry:'2027-01-01',quantity:5,minimum:1,location:'Lemari',storageCondition:'Sesuai label'});for(const k of ['packagingChecked','expiryChecked'])$(`[name=${k}]`).checked=true;failAfterCommit=true;await click('#saveStock');assert.match($('.teacher-errors').textContent,/jaringan/);assert.equal(Object.values(read('health/year/stock'))[0].quantity,5);await click('#saveStock');assert.equal(Object.values(read('health/year/stock'))[0].quantity,5);assert.equal(Object.keys(read('health/year/transactions')).length,1);});
