import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {webcrypto} from 'node:crypto';
const require=createRequire(import.meta.url),{JSDOM}=require(process.env.MADANI_JSDOM_MODULE||'jsdom'),base=new URL('../',import.meta.url),dom=new JSDOM('<main id="content"></main>',{url:'http://localhost/app/index.html'}),win=dom.window;
// jsdom has no browser top layer; exercise the native dialog lifecycle contract.
win.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
win.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new win.Event('close'));};
let db={},writes=[];const read=p=>p.split('/').reduce((v,k)=>v?.[k],db)||null;const put=(p,v)=>{const parts=p.split('/');let o=db;for(const k of parts.slice(0,-1))o=o[k]??={};o[parts.at(-1)]=v;writes.push(p);};
const repository={getNode:async p=>read(p),listNode:async p=>Object.entries(read(p)||{}).map(([id,r])=>({id,...r})),saveTeacherSession:async(p,r,o)=>{if((read(p)?.version||0)!==o.expectedVersion)throw Error('Data berubah');put(p,r);return r;}};
const context=vm.createContext({console,document:win.document,window:win,FormData:win.FormData,Intl,Date,URL,crypto:webcrypto,setTimeout,clearTimeout});const exports=Object.keys(repository),mock=new vm.SyntheticModule(exports,function(){for(const k of exports)this.setExport(k,repository[k]);},{context}),cache=new Map();async function load(url){if(url.endsWith('/repository.js'))return mock;if(cache.has(url))return cache.get(url);const m=new vm.SourceTextModule(readFileSync(fileURLToPath(url),'utf8'),{context,identifier:url});cache.set(url,m);await m.link((s,p)=>load(new URL(s,p.identifier).href));return m;}
const mod=await load(new URL('assets/js/mentoring.js',base).href);await mod.evaluate();const M=mod.namespace,ctx={root:win.document.querySelector('main'),yearId:'year',session:{activeRole:'guru_wali',roles:['guru_wali'],user:{uid:'mentor1'},profile:{name:'Guru Wali',staffId:'staff',menteeStudentIds:['s1']}},master:{students:[{id:'s1',name:'Santri Satu'},{id:'s2',name:'Di luar penugasan'}],classes:[{id:'c',name:'VII'}],classAssignments:{s1:{classId:'c'}}},navigate:()=>{}};
const $=s=>ctx.root.querySelector(s);async function flush(){for(let i=0;i<50;i++)await Promise.resolve();}async function click(s){$(s).click();await flush();}
test('mentoring rubric required; same-day update keeps one session and result lives on same record',async()=>{db={};writes=[];await M.renderMentorForm(ctx);assert.equal(ctx.root.querySelectorAll('[data-student]').length,1);await click('[data-student=s1]');if(process.env.MADANI_VISUAL_QA){mkdirSync('outputs/qa',{recursive:true});writeFileSync('outputs/qa/mentor-mobile.html','<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Guru Wali — data uji</title>'+['app','portal','teacher','mentoring','brand-theme'].map(n=>`<link rel="stylesheet" href="/assets/css/${n}.css?v=39">`).join('')+'<body style="margin:auto;max-width:390px;padding:12px">'+ctx.root.innerHTML+'</body>');}await click('#saveMentoring');assert.match($('.mu-error').textContent,/indikator/);for(const el of ctx.root.querySelectorAll('.mu-options input[value="3"]'))el.checked=true;for(const id of ['appreciation','target','strongWhy','strategy'])$('#'+id).value='Contoh '+id;await click('#saveMentoring');const basePath='boarding/mentoring/year/s1';assert.equal(Object.keys(read(basePath)).length,1);const id=Object.keys(read(basePath))[0];assert.equal(Object.keys(read(basePath)[id].clarification.answers).length,12);$('#target').value='Target baru';await click('#saveMentoring');assert.equal(Object.keys(read(basePath)).length,1);await M.renderMentorHistory(ctx);await click('[data-result]');assert.equal($('#resultSheet').tagName,'DIALOG');assert.equal($('#resultSheet').open,true);$('[name=resultStatus][value=TERCAPAI]').checked=true;$('[name=description]').value='Terlihat perkembangannya';$('#resultForm').dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(read(basePath)[id].targetResultStatus,'TERCAPAI');assert.equal($('#resultSheet').open,false);await M.renderMentorForm(ctx);await click('[data-student=s1]');assert.equal($('#target').value,'Target baru');await click('#saveMentoring');assert.equal(read(basePath)[id].targetResultStatus,'TERCAPAI');});
test('history filtering and reassignment prevent editing outside current mentor roster',async()=>{await M.renderMentorHistory(ctx);$('#startDate').value='2099-01-01';$('#endDate').value='2099-02-01';$('#endDate').dispatchEvent(new win.Event('change'));await flush();assert.equal(ctx.root.querySelectorAll('[data-result]').length,0);const other={...ctx,master:{...ctx.master,mentorAssignments:{s1:{status:'active',mentorStaffId:'other'}}}};await M.renderMentorForm(other);assert.equal(ctx.root.querySelectorAll('[data-student]').length,0);});
test('interview scores update immediately, handle partial answers and ties, and reload saved answers',async()=>{
 db={};await M.renderMentorForm(ctx);await click('[data-student=s1]');
 assert.match($('.mu-indicator p').textContent,/Kalau sudah mendekati waktu salat/);
 assert.match($('#dimensionScores').textContent,/Skor muncul otomatis/);
 const choose=(name,value)=>{const el=$(`input[name=${name}][value="${value}"]`);el.checked=true;el.dispatchEvent(new win.Event('change',{bubbles:true}));};
 choose('sp1',2);assert.match($('[data-dimension-score=spiritual]').textContent,/2 \/ 5.*sementara/);
 choose('sp2',4);assert.match($('[data-dimension-score=spiritual]').textContent,/3 \/ 5/);
 choose('sp3',3);assert.doesNotMatch($('[data-dimension-score=spiritual]').textContent,/sementara/);
 choose('em1',3);assert.equal(ctx.root.querySelectorAll('.mu-score-card.lowest').length,2);
 choose('em2',1);assert.equal(ctx.root.querySelectorAll('.mu-score-card.lowest').length,1);assert.equal($('.mu-score-card.lowest').dataset.scoreCard,'emosional');
 for(const el of ctx.root.querySelectorAll('.mu-options input[value="3"]'))if(!ctx.root.querySelector(`input[name=${el.name}]:checked`))choose(el.name,3);
 for(const id of ['appreciation','target','strongWhy','strategy'])$('#'+id).value='Jawaban wawancara';
 await click('#saveMentoring');const record=Object.values(read('boarding/mentoring/year/s1'))[0];assert.equal(record.clarification.sourceVersion,'MENTOR_INTERVIEW_V1');assert.equal(record.clarification.scores.find(d=>d.id==='emosional').score,2);
 await M.renderMentorForm(ctx);await click('[data-student=s1]');assert.match($('[data-dimension-score=emosional]').textContent,/2 \/ 5/);assert.doesNotMatch($('#dimensionScores').textContent,/sementara/);
 $('#mentoringDate').value='2026-01-01';$('#mentoringDate').dispatchEvent(new win.Event('change'));await flush();assert.match($('#dimensionScores').textContent,/Skor muncul otomatis/);
});
