import test from 'node:test';import assert from 'node:assert/strict';
import {teacherSchedules,localClock,verifyLocation,learningTransition,weightedScore,tahsinScore,tahfizQuality,meetingDates} from '../assets/js/teacher/model.js';
import K from '../assets/js/teacher/weekly-kpi.js';
import {programPlacement,programEligible,subjectEligible} from '../assets/js/teacher/program-placement.js';
test('Quran placement uses stable IDs, year and effective date; dedicated exam schemas cannot use unrelated subjects',()=>{
 const records={a:{studentId:'s',academicYearId:'y',effectiveFrom:'2026-07-01',programQuran:'TAHSIN',tahsinLevel:'LEVEL_1'},b:{studentId:'s',academicYearId:'y',effectiveFrom:'2026-10-01',programQuran:'TAHFIZ',tahsinLevel:'LEVEL_3'},c:{studentId:'s',academicYearId:'other',effectiveFrom:'2026-10-02',programQuran:'TAHSIN'}};
 const before=programPlacement('s','2026-09-30',records,'y'),after=programPlacement('s','2026-10-02',records,'y');
 assert.equal(programEligible('tahsin_level_1',before),true);assert.equal(programEligible('tahsin_level_2',before),false);assert.equal(programEligible('tahfiz',before),false);
 assert.equal(after.tahsinLevel,null);assert.equal(programEligible('tahfiz',after),true);assert.equal(programEligible('Tahfiz',programPlacement('unknown','2026-10-02',records,'y')),true);
 assert.equal(subjectEligible('bahasa_arab','Matematika'),false);assert.equal(subjectEligible('kitab_tanpa_praktek','Bahasa Arab'),false);assert.equal(subjectEligible('tahsin_level_2','Al-Qur’an'),true);
});
const ctx={yearId:'year',session:{user:{uid:'u'},profile:{staffId:'t',classIds:['c'],subjectIds:['m']}},master:{classes:[{id:'c',unitId:'sd'},{id:'other',unitId:'smp'}],subjects:[{id:'m',unitId:'sd'}],academicSchedules:[{id:'s',classId:'c',subjectId:'m',day:'Senin',startTime:'08.00',academicYearId:'year'}]}};
test('official schedules only: no generated examples or another teacher assignment',()=>{assert.equal(teacherSchedules(ctx)[0].id,'s');assert.equal(teacherSchedules(ctx).length,1);assert.equal(teacherSchedules({...ctx,master:{...ctx.master,academicSchedules:[]}}).length,0);assert.equal(teacherSchedules({...ctx,master:{...ctx.master,academicSchedules:[{...ctx.master.academicSchedules[0],staffId:'another'}]}}).length,0);assert.equal(teacherSchedules({...ctx,session:{user:{uid:'u'},profile:{}}}).length,0);});
test('Makassar clock handles UTC day boundary and meeting calendar spans selected semester',()=>{assert.equal(localClock(new Date('2026-10-01T16:01:00Z')).date,'2026-10-02');const dates=meetingDates(2026,1,['Senin'],['2026-07-06']);assert.ok(!dates.includes('2026-07-06'));assert.ok(dates.every(d=>d>='2026-07-01'&&d<='2026-12-31'));assert.equal(K.weekOf('2026-10-04').weekStart,'2026-10-05');});
test('GPS fails without Madani configuration, enforces radius with reference accuracy tolerance',()=>{const c={latitude:-8,longitude:116,accuracy:12},z={id:'madani',latitude:-8,longitude:116,radiusMeter:700};assert.throws(()=>verifyLocation(c,null),/belum dikonfigurasi/);assert.equal(verifyLocation(c,z).distance,0);assert.throws(()=>verifyLocation({...c,latitude:-7},z),/luar zona/);assert.throws(()=>verifyLocation({...c,accuracy:NaN},z),/valid/);});
const info={roster:[{id:'s1'},{id:'s2'}],schedule:{id:'j',classId:'c',subjectId:'m',academicYearId:'year'},date:'2026-10-02',actor:{staffId:'t',uid:'u'},subjectName:'Matematika'};
test('two-stage learning finalizes only missing students and preserves locked attendance during score edits',()=>{const first=learningTransition(null,{students:{s1:{status:'Hadir'},s2:{status:'Belum Hadir'}}},info);assert.equal(first.stage,'AWAL');assert.equal(first.students.s1.points,30);assert.throws(()=>learningTransition(first,{students:{s1:{status:'Alfa'},s2:{status:'Belum Hadir'}}},info),/Tentukan status/);const final=learningTransition(first,{students:{s1:{status:'Alfa',score:''},s2:{status:'Terlambat',score:65}}},info);assert.equal(final.students.s1.status,'Hadir');assert.equal(final.students.s1.score,null);assert.equal(final.students.s2.points,-20);const edited=learningTransition(final,{students:{s1:{status:'Alfa',score:80},s2:{status:'Hadir',score:70}}},info);assert.equal(edited.students.s2.status,'Terlambat');assert.equal(edited.students.s1.score,80);});
test('material requirement activates only when targets exist and exempts Quran',()=>{const data={students:{s1:{status:'Hadir'},s2:{status:'Hadir'}}};assert.throws(()=>learningTransition(null,data,{...info,targets:[{id:'mat'}]}),/Pilih materi/);assert.equal(learningTransition(null,data,{...info,subjectName:'Tahfiz',targets:[{id:'mat'}]}).students.s1.points,40);assert.throws(()=>learningTransition(null,{...data,materialIds:['outsider']},{...info,targets:[{id:'mat'}]}),/bukan milik/);});
test('weighted exams preserve missing values; Tahsin and Tahfiz use source grading rules',()=>{assert.equal(weightedScore('kitab_dengan_praktek',{Lisan:80,Tulisan:70,Praktek:90,Tashnif:100}),84);assert.equal(weightedScore('bahasa_arab',{Lisan:0,Tulisan:''}),null);assert.equal(weightedScore('bahasa_arab',{Lisan:0,Tulisan:0}),0);assert.throws(()=>weightedScore('bahasa_arab',{Lisan:101,Tulisan:0}),/0–100/);assert.deepEqual(tahsinScore([3,3,3,3]),{score:75,quality:'JAYYID'});assert.equal(tahfizQuality(7),'BIMBINGAN');});
test('weekly KPI never grants reward from operational evidence alone or missing observations',()=>{const operational=Object.fromEntries(K.CONFIG.GURU.operational.map(([id])=>[id,100]));const partial=K.calculate('GURU',{operational});assert.equal(partial.total,null);assert.equal(partial.rewardEligible,false);const full={operational,observations:[{scores:[5,5,5,5,5],subject:'m'}],exemplaryRecord:{scores:[4,4,4,4,4]},closure:{closedAt:'now'}};assert.equal(K.calculate('GURU',full).total,100);assert.equal(K.calculate('GURU',full).rewardEligible,true);assert.equal(K.calculate('GURU',{...full,criticalFailures:[{active:true}]}).rewardEligible,false);assert.equal(K.scoreOperational('GURU',{attendance:{value:null}}).score,null);});

test('saved example rows never enter operational teacher schedules',()=>{const example={...ctx.master.academicSchedules[0],isExample:true};assert.equal(teacherSchedules({...ctx,master:{...ctx.master,academicSchedules:[example]}}).length,0);});

test('consecutive lessons merge into one session, but breaks, classes and teachers stay separate',()=>{
 const base={academicYearId:'y',day:'Senin',subjectId:'bahasa',classId:'putra8',teacherStaffId:'t',assignmentConfirmed:true};
 const slots=[{...base,id:'a',startTime:'08:00',endTime:'08:40'},{...base,id:'b',startTime:'08:40',endTime:'09:20'},{...base,id:'c',startTime:'09:20',endTime:'10:00'},{...base,id:'d',startTime:'10:20',endTime:'11:00'},{...base,id:'e',classId:'putri8',startTime:'11:00',endTime:'11:40'},{...base,id:'f',teacherStaffId:'other',startTime:'11:00',endTime:'11:40'}];
 const result=mergeConsecutiveSchedules(slots);assert.equal(result.length,4);assert.equal(result[0].id,'a');assert.equal(result[0].endTime,'10:00');assert.deepEqual(result[0].sourceScheduleIds,['a','b','c']);assert.equal(slots[0].endTime,'08:40');assert.deepEqual(attendanceForSchedule({b:{status:'TERLAMBAT'}},result[0]),{status:'TERLAMBAT'});
});
import {mergeConsecutiveSchedules,attendanceForSchedule} from '../assets/js/teacher/model.js';
