import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {webcrypto} from 'node:crypto';
const require=createRequire(import.meta.url),{JSDOM}=require(process.env.MADANI_JSDOM_MODULE||'jsdom'),base=new URL('../',import.meta.url),dom=new JSDOM('<main id="content"></main>',{url:'http://localhost/app/index.html'}),win=dom.window;
win.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};win.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new win.Event('close'));};
let db={},writes=[];
const read=path=>path.split('/').filter(Boolean).reduce((o,k)=>o?.[k],db)||null;
const put=(path,value)=>{const parts=path.split('/').filter(Boolean);let parent=db;parts.slice(0,-1).forEach(k=>parent=parent[k]??={});parent[parts.at(-1)]=value;writes.push(path);};
const repository={setNode:async(p,v)=>put(p,v),transitionWorkspaceRecord:async(path,id,fn)=>{const r=fn(read(path+'/'+id));put(path+'/'+id,r);return r;},getNode:async p=>read(p),getCurrentAcademicYearId:async()=> 'TA-2026-2027-GANJIL',listNode:async p=>Object.entries(read(p)||{}).map(([id,r])=>({id,...r})),saveTeacherSession:async(path,data,opts={})=>{const old=read(path);if(opts.createOnly&&old)return old;if(opts.expectedVersion!==null&&opts.expectedVersion!==undefined&&(old?.version||0)!==opts.expectedVersion)throw Error('Data telah berubah.');const r={...data,createdAt:old?.createdAt||Date.now(),createdBy:old?.createdBy||opts.actorUid,updatedAt:Date.now()};put(path,r);return r;},patchNode:async(p,changes)=>{for(const [key,val]of Object.entries(changes))put([p,key].filter(Boolean).join('/'),val);},pushRecord:async(path,data)=>{const id=webcrypto.randomUUID();put(path+'/'+id,data);return{id,...data};}};
const names=[...readFileSync(new URL('assets/js/repository.js',base),'utf8').matchAll(/export (?:async )?function (\w+)/g)].map(m=>m[1]);
const context=vm.createContext({console,document:win.document,window:win,navigator:{geolocation:{getCurrentPosition:resolve=>resolve({coords:{latitude:-8,longitude:116,accuracy:10}})}},sessionStorage:win.sessionStorage,localStorage:win.localStorage,FormData:win.FormData,Event:win.Event,crypto:webcrypto,Intl,Date,URL,URLSearchParams,setTimeout,clearTimeout});
const mock=new vm.SyntheticModule(names,function(){for(const name of names)this.setExport(name,repository[name]||(()=>{throw Error('Unexpected '+name)}));},{context}),cache=new Map();async function load(url){if(url.endsWith('/repository.js'))return mock;if(cache.has(url))return cache.get(url);const m=new vm.SourceTextModule(readFileSync(fileURLToPath(url),'utf8'),{context,identifier:url});const ready=m.link((s,p)=>load(new URL(s,p.identifier).href)).then(()=>m);cache.set(url,ready);return ready;}
const mod=await load(new URL('assets/js/teacher/routes.js',base).href);await mod.evaluate();const home=await load(new URL('assets/js/teacher/home.js',base).href);await home.evaluate();const model=await load(new URL('assets/js/teacher/model.js',base).href);await model.evaluate();const now=model.namespace.localClock();
const ctx={yearId:'TA-2026-2027-GANJIL',session:{activeRole:'guru_mapel',roles:['guru_mapel'],user:{uid:'teacher'},profile:{staffId:'staff1',name:'Guru Uji',unitIds:['u1'],classIds:['c1'],subjectIds:['m1','m2']}},root:win.document.querySelector('#content'),navigate:()=>{},master:{classes:[{id:'c1',name:'Kelas Uji',unitId:'u1'}],subjects:[{id:'m1',name:'Matematika',unitId:'u1'},{id:'m2',name:'Tahfiz',unitId:'u1'}],students:[{id:'s1',name:'Santri Satu'},{id:'s2',name:'Santri Dua'}],classAssignments:{s1:{classId:'c1'},s2:{classId:'c1'}},groupAssignments:{g1:{s1:true,s2:true}},groups:[{id:'g1',name:'Halaqah Binaan',programType:'quran',mentorStaffId:'staff1'}],academicSchedules:[{id:'j1',academicYearId:'TA-2026-2027-GANJIL',classId:'c1',subjectId:'m1',unitId:'u1',day:now.day,startTime:'08:00',endTime:'08:45'},{id:'j2',classId:'c1',subjectId:'m2',unitId:'u1',day:now.day,startTime:'09:00',endTime:'09:45'}]}};
const routes=mod.namespace.TEACHER_ROUTES;const quranModule=await load(new URL('assets/js/teacher/quran.js',base).href);await quranModule.evaluate();const renderQuran=ctx=>quranModule.namespace.renderTeacherQuran({...ctx,session:{...ctx.session,activeRole:'mentor_tahsin_tahfiz',roles:['mentor_tahsin_tahfiz']}});const $=q=>ctx.root.querySelector(q);async function settle(){for(let i=0;i<30;i++)await Promise.resolve();}async function click(q){assert.ok($(q),'Missing '+q);$(q).click();await settle();}function change(q,value){$(q).value=value;$(q).dispatchEvent(new win.Event('change',{bubbles:true}));}const prefix=`academic/learning_sessions/${ctx.yearId}/staff1/${now.date}/j1`;
test('all dedicated teacher pages render using Madani IDs and no Firebase writes',async()=>{db={};writes=[];for(const [id,render]of Object.entries(routes)){await render(ctx);assert.ok(ctx.root.textContent.trim(),id);assert.equal(ctx.root.querySelectorAll('script').length,0);}await home.namespace.renderTeacherHome(ctx);assert.equal(ctx.root.querySelectorAll('.hub-quick-card').length,4);assert.equal(ctx.root.querySelectorAll('.hub-menu-card').length,6);const quickIds=new Set([...ctx.root.querySelectorAll('[data-quick]')].map(b=>b.dataset.quick));assert.ok([...ctx.root.querySelectorAll('.hub-menu-card')].every(b=>!quickIds.has(b.dataset.route)));assert.equal(writes.length,0);});
test('GPS sheet refuses missing configuration then saves per schedule once',async()=>{db={};await home.namespace.renderTeacherHome(ctx);await home.namespace.openSchedule(ctx);await click('[data-attend="j1"]');assert.match($('.teacher-sheet .teacher-errors').textContent,/belum dikonfigurasi/);put('settings/teacherAttendance',{locations:{campus:{latitude:-8,longitude:116,radiusMeter:700}}});await click('[data-attend="j1"]');const p=`academic/teaching_attendance/${ctx.yearId}/staff1/${now.date}/j1`;assert.equal(read(p).scheduleId,'j1');assert.equal(read(p).method,'GPS_OTOMATIS');const time=read(p).createdAt;await home.namespace.renderTeacherHome(ctx);await home.namespace.openSchedule(ctx);assert.equal($('[data-attend="j1"]'),null);assert.equal(read(p).createdAt,time);});
test('learning transitions save initial and final on same schedule without overwriting daily legacy attendance',async()=>{db={};await routes['student-attendance'](ctx);await click('[data-schedule="j1"]');$('[data-student="s2"] input[value="Belum Hadir"]').checked=true;await click('#saveLearning');assert.equal(read(prefix).stage,'AWAL');await click('#saveLearning');assert.match($('.teacher-errors').textContent,/Tentukan status/);$('[data-student="s2"] input[value="Terlambat"]').checked=true;await click('#saveLearning');assert.equal(read(prefix).stage,'FINAL');assert.equal(read(prefix).students.s2.status,'Terlambat');assert.equal(read('academic/student_attendance'),null);assert.equal($('#saveLearning').textContent,'Simpan Nilai & Materi');});
test('material calendar saves by meeting and requires cause and followup for unmet targets',async()=>{db={};await routes['lesson-plans'](ctx);const input=$('[data-date]');assert.ok(input);input.value='Bilangan';const targetDate=input.dataset.date;await click('#saveMaterials');const p=`academic/material_targets/${ctx.yearId}/staff1/c1__m1/semester_1`;assert.equal(read(p)[targetDate].material,'Bilangan');await click('[data-mode="report"]');$('[data-target]').checked=true;change('#completionStatus','BELUM_TERCAPAI');await click('#saveCompletion');assert.match($('.teacher-errors').textContent,/analisa/);$('#cause').value='Perlu latihan';$('#followUp').value='Pertemuan tambahan';await click('#saveCompletion');assert.equal(read(`academic/material_completions/${ctx.yearId}/staff1/c1__m1/semester_1__${targetDate}`).status,'BELUM_TERCAPAI');});
test('exam blank values remain missing and final requires review; low grades reach follow-up',async()=>{db={};await routes.grades(ctx);await click('[data-schema="kitab_tanpa_praktek"]');await click('[data-assignment="c1__m1"]');await click('[data-type="bulanan"]');await click('[data-period]');await click('#saveDraft');const exams=read(`academic/exam_sessions/${ctx.yearId}/staff1`);assert.equal(Object.values(exams)[0].students.s1.score,null);for(const input of ctx.root.querySelectorAll('[data-component]'))input.value='60';await click('#finalizeGrades');assert.equal($('#confirmFinal').disabled,true);$('#reviewed').checked=true;$('#reviewed').dispatchEvent(new win.Event('change'));await click('#confirmFinal');assert.equal(Object.values(read(`academic/exam_sessions/${ctx.yearId}/staff1`))[0].stage,'FINAL');assert.equal($('#saveDraft').disabled,true);await routes['academic-followup'](ctx);assert.equal(ctx.root.querySelectorAll('[data-follow]').length,2);await click('[data-follow]');$('#clarification').value='Konsep belum dikuasai';$('#target').value='Nilai 80';$('#strategy').value='Latihan';await click('#save');assert.equal(Object.values(read(`academic/exam_followups/${ctx.yearId}/staff1`))[0].status,'Dalam Proses');});
test('Quran uses existing school students and validates surah bounds before saving',async()=>{db={};await renderQuran(ctx);assert.equal(ctx.root.querySelectorAll('[data-student]').length,2);$('[data-student="s1"] [data-lines]').value='2';$('[data-student="s1"] [data-end]').value='8';await click('[data-student="s1"] [data-save]');assert.match($('.teacher-errors').textContent,/Rentang ayat/);$('[data-student="s1"] [data-end]').value='7';await click('[data-student="s1"] [data-save]');assert.equal(Object.values(read(`academic/quran_records/${ctx.yearId}/g1/s1`))[0].totalVerses,7);assert.equal(read('students'),null);assert.equal($('[data-student="s1"] [data-save]').disabled,true);});
test('writing sanitizes script and unsafe links; saved article can be edited',async()=>{db={};const writing=await load(new URL('assets/js/teacher/writing.js',base).href);await writing.evaluate();assert.equal(writing.namespace.safeArticleHtml('<script>alert(1)</script><p onclick="x()">Hello</p>'),'<p>Hello</p>');assert.throws(()=>writing.namespace.driveUrl('javascript:alert(1)'),/HTTPS/);await routes['teacher-writing'](ctx);$('#writingTitle').value='Catatan Uji';$('#writingEditor').textContent='Materi pembelajaran untuk pertemuan pertama.';await click('#saveWriting');const records=read(`academic/teacher_writings/${ctx.yearId}/staff1`);assert.equal(Object.keys(records).length,1);$('#writingTitle').value='Catatan Diperbarui';await click('#saveWriting');assert.equal(Object.keys(read(`academic/teacher_writings/${ctx.yearId}/staff1`)).length,1);});
test('multi-student teacher report uses existing counselor inbox and one incident ID',async()=>{db={};await routes['teacher-case'](ctx);for(const checkbox of ctx.root.querySelectorAll('[data-student]'))checkbox.checked=true;$('#reportSource').value='langsung';$('#reportCategory').value='Kedisiplinan';$('#reportDescription').value='Kronologi simulasi';await click('#sendReport');const cases=Object.values(read(`boarding/cases/${ctx.yearId}`));assert.equal(cases.length,2);assert.equal(new Set(cases.map(r=>r.groupId)).size,1);assert.ok(cases.every(r=>r.status==='menunggu_konselor'&&r.parentVisible===false));assert.equal(read('students'),null);});
test('teacher reflections require all 12 ratings and store objective evidence separately',async()=>{db={};await routes['teacher-assessment'](ctx);assert.equal(ctx.root.querySelectorAll('[data-rating]').length,12);await click('#saveAssessment');assert.match($('.teacher-errors').textContent,/Lengkapi/);for(const input of ctx.root.querySelectorAll('[data-rating]'))input.value='4';await click('#saveAssessment');const r=Object.values(read(`academic/teacher_reflections/${ctx.yearId}/staff1`))[0];assert.equal(Object.keys(r.ratings).length,12);assert.equal(r.objective.length,7);assert.equal(read('academic/weekly_kpi'),null);});
test('parent read model sees published snapshots only and student-specific learning rows',async()=>{db={};const readModel=await load(new URL('assets/js/teacher/read-model.js',base).href);await readModel.evaluate();put(`academic/learning_sessions/${ctx.yearId}/staff1/day/j1`,{scheduleId:'j1',date:now.date,subjectId:'m1',students:{s1:{status:'Hadir'},s2:{status:'Alfa'}}});put(`academic/exam_sessions/${ctx.yearId}/staff1/final`,{schema:'bahasa_arab',stage:'FINAL',students:{s1:{score:80},s2:{score:60}}});put(`academic/exam_sessions/${ctx.yearId}/staff1/draft`,{schema:'bahasa_arab',stage:'DRAFT',students:{s1:{score:90}}});put(`academic/report_publications/${ctx.yearId}/s1/bulanan__2026-10`,{status:'PUBLISHED',type:'bulanan',period:'2026-10',rows:[{subjectId:'m1',score:80}]});put(`academic/report_publications/${ctx.yearId}/s1/semester__1`,{status:'WITHDRAWN',rows:[{score:99}]});const learning=await readModel.namespace.learningForStudent(ctx.yearId,'s1'),exams=await readModel.namespace.examsForStudent(ctx.yearId,'s1');assert.equal(learning.length,1);assert.equal(learning[0].status,'Hadir');assert.equal(exams.length,1);assert.equal(exams[0].score,80);});
test('Quran roster follows historical placement and dedicated exams exclude unrelated subjects',async()=>{
 db={};put('academic/quran_placements/first',{studentId:'s1',academicYearId:ctx.yearId,programQuran:'TAHSIN',tahsinLevel:'LEVEL_1',effectiveFrom:'2026-01-01'});
 await renderQuran(ctx);assert.ok($('[data-student="s1"] [data-quality-score]'));assert.ok($('[data-student="s2"] [data-lines]'));
 await renderQuran(ctx);assert.ok($('[data-student="s1"] [data-quality-score]'));assert.ok($('[data-student="s2"] [data-lines]'));
 change('#quranDate','2025-12-31');await settle();assert.ok($('[data-student="s1"] [data-lines]'));
 await routes.grades(ctx);await click('[data-schema="bahasa_arab"]');assert.equal($('[data-assignment="c1__m1"]'),null);
});
test('combined lesson records both class rosters under one teacher attendance session',async()=>{
 db={};const combined={...ctx,master:{...ctx.master,classes:[...ctx.master.classes,{id:'c2',name:'Kelas Kedua',unitId:'u1'}],classAssignments:{s1:{classId:'c1'},s2:{classId:'c2'}},academicSchedules:['c1','c2'].map((classId,i)=>({id:'source-'+i,classId,subjectId:'m1',teacherStaffId:'staff1',day:now.day,startTime:'08:00',endTime:'08:40',combinedClassIds:['c1','c2'],teachingSessionId:'combined'}))}};
 await routes['student-attendance'](combined);assert.equal(ctx.root.querySelectorAll('[data-schedule]').length,1);await click('[data-schedule="combined"]');assert.equal(ctx.root.querySelectorAll('[data-student]').length,2);await click('#saveLearning');
 const saved=read(`academic/learning_sessions/${ctx.yearId}/staff1/${now.date}/combined`);assert.deepEqual(Object.keys(saved.students).sort(),['s1','s2']);assert.equal(saved.classIds.length,2);
});

test('attendance refreshes master before selecting official schedules and does not fall back after read failure',async()=>{
 const original=ctx.master;let refreshed=0;const c={...ctx,master:{...original,academicSchedules:[]},refreshMaster:async()=>{refreshed++;c.master=original;}};
 await home.namespace.openSchedule(c);assert.equal(refreshed,1);assert.ok($('[data-attend="j1"]'));assert.doesNotMatch(ctx.root.textContent,/Contoh otomatis/);
 await home.namespace.openSchedule({...ctx,refreshMaster:async()=>{throw Error('Jaringan terputus');}});assert.match(ctx.root.textContent,/Data tidak dapat dimuat: Jaringan terputus/);assert.equal([...ctx.root.querySelectorAll('dialog[open]')].at(-1).querySelectorAll('[data-attend]').length,0);
});

test('consecutive timetable slots render one learning session and save attendance once',async()=>{
 db={};const schedule={...ctx.master.academicSchedules[0],day:now.day,subjectId:'m1',id:'block1',startTime:'08:00',endTime:'08:40'},c={...ctx,master:{...ctx.master,academicSchedules:[schedule,{...schedule,id:'block2',startTime:'08:40',endTime:'09:20'},{...schedule,id:'block3',startTime:'09:20',endTime:'10:00'}]}};
 await routes['student-attendance'](c);assert.equal(ctx.root.querySelectorAll('[data-schedule]').length,1);assert.match(ctx.root.textContent,/08:00–10:00/);await click('[data-schedule="block1"]');await click('#saveLearning');const sessions=read(`academic/learning_sessions/${ctx.yearId}/staff1/${now.date}`);assert.equal(Object.keys(sessions).length,1);assert.deepEqual(Array.from(sessions.block1.sourceScheduleIds),['block1','block2','block3']);assert.equal(sessions.block1.endTime,'10:00');
 // An earlier record on a later slot remains authoritative and does not cause a new duplicate.
 db={};put(`academic/learning_sessions/${ctx.yearId}/staff1/${now.date}/block2`,{...sessions.block1,scheduleId:'block2',version:1});await routes['student-attendance'](c);await click('[data-schedule="block1"]');assert.match($('#saveLearning').textContent,/Finalisasi/);await click('#saveLearning');assert.deepEqual(Object.keys(read(`academic/learning_sessions/${ctx.yearId}/staff1/${now.date}`)),['block2']);
});

test('teacher can report students outside teaching classes and units without a timetable',async()=>{
 db={};const reporting={...ctx,master:{...ctx.master,academicSchedules:[],students:[...ctx.master.students,{id:'outside',name:'Santri Unit Lain',unitId:'u2',status:'active'},{id:'duplicate',name:'Duplikat',status:'inactive',mergedInto:'outside'}],classAssignments:{}}};
 await routes['teacher-case'](reporting);assert.ok($('[data-student="outside"]'));assert.equal($('[data-student="duplicate"]'),null);
 $('[data-student="outside"]').checked=true;$('#reportSource').value='langsung';$('#reportCategory').value='Kedisiplinan';$('#reportDescription').value='Kejadian lintas unit';await click('#sendReport');const records=Object.values(read(`boarding/cases/${ctx.yearId}`));assert.equal(records.length,1);assert.equal(records[0].studentId,'outside');assert.equal(records[0].reportedByUid,'teacher');assert.equal(records[0].status,'menunggu_konselor');
});

test('Tahfiz uses assigned halaqah only even when teacher has Quran class schedules',async()=>{
 db={};await renderQuran(ctx);
 assert.deepEqual([...$('#quranScope').options].map(o=>o.value),['g1']);
 const noGroup={...ctx,master:{...ctx.master,groups:[]}};await renderQuran(noGroup);
 assert.equal(ctx.root.querySelectorAll('[data-student]').length,0);
 assert.match(ctx.root.textContent,/Belum ada halaqah/);
});
test('Tahsin halaqah includes unplaced members and excludes students from class only',async()=>{
 db={};const tahsin={...ctx,master:{...ctx.master,groups:[{id:'g1',name:'Tahsin — Pembina',programType:'quran',type:'Tahsin',mentorStaffId:'staff1'}],groupAssignments:{g1:{s1:true}}}};
 await renderQuran(tahsin);assert.equal($('#quranProgram'),null);assert.ok($('[data-student="s1"]'));assert.equal($('[data-student="s2"]'),null);
 assert.equal(quranModule.namespace.halaqahEligible('Tahsin',{},{name:'Tahsin & Tahfiz'}),true);
 assert.equal(quranModule.namespace.halaqahEligible('Tahfiz',{},{name:'Tahsin & Tahfiz'}),true);
});
test('Quran multiple-surah mode saves expanded portions and validates last verse',async()=>{
 db={};await renderQuran(ctx);assert.equal($('[data-deep]'),null);
 await click('[data-student="s1"] [data-portion-mode="range"]');
 change('[data-student="s1"] [data-first]','112');change('[data-student="s1"] [data-last]','113');
 $('[data-student="s1"] [data-last-verse]').value='7';$('[data-student="s1"] [data-lines]').value='2';await click('[data-student="s1"] [data-save]');assert.match($('.teacher-errors').textContent,/ayat terakhir/);
 $('[data-student="s1"] [data-last-verse]').value='6';$('[data-student="s1"] [data-last-verse]').dispatchEvent(new win.Event('input',{bubbles:true}));
 assert.equal($('[data-student="s1"] [data-total]').textContent,'11');await click('[data-student="s1"] [data-save]');
 const record=Object.values(read(`academic/quran_records/${ctx.yearId}/g1/s1`))[0];assert.equal(record.portions.length,2);assert.equal(record.totalVerses,11);assert.equal('deepReflection' in record,false);
});
test('Quran manual drafts survive mode changes and reverse surah range works for Tahsin',async()=>{
 db={};await renderQuran(ctx);$('[data-student="s1"] [data-end]').value='4';await click('[data-student="s1"] [data-portion-mode="range"]');await click('[data-student="s1"] [data-portion-mode="manual"]');assert.equal($('[data-student="s1"] [data-end]').value,'4');
 await click('[data-student="s1"] [data-add]');assert.equal($('[data-student="s1"]').querySelectorAll('[data-portion]').length,2);
 put('academic/quran_placements/p',{studentId:'s1',academicYearId:ctx.yearId,programQuran:'TAHSIN',effectiveFrom:'2020-01-01'});await renderQuran(ctx);await click('[data-student="s1"] [data-portion-mode="range"]');change('[data-student="s1"] [data-first]','113');change('[data-student="s1"] [data-last]','112');$('[data-student="s1"] [data-last-verse]').value='2';await click('[data-student="s1"] [data-save]');
 const r=Object.values(read(`academic/quran_records/${ctx.yearId}/g1/s1`))[0];assert.equal(r.totalVerses,8);assert.equal(r.portions[0].surah,113);assert.equal(r.portions[1].end,2);
});

test('Quran form takes activity from the home card without a program selector',async()=>{
 db={};await renderQuran(ctx);assert.equal($('#quranProgram'),null);assert.match(ctx.root.textContent,/Setoran Ziyadah/);assert.equal($('#murojaahField').hidden,true);await quranModule.namespace.renderTeacherQuran({...ctx,session:{...ctx.session,activeRole:'mentor_tahsin_tahfiz'}},'Murojaah');assert.equal($('#quranProgram'),null);assert.match(ctx.root.textContent,/Setoran Muroja’ah/);assert.equal($('#murojaahField').hidden,false);assert.ok($('[data-student="s1"] [data-lines]'));
});

test('Tahfiz home has setoran and attendance cards that open the matching Quran activity',async()=>{
 const homeModule=await load(new URL('assets/js/tahfiz-home.js',base).href);await homeModule.evaluate();const visited=[];await homeModule.namespace.renderTahfizHome({...ctx,navigate:r=>visited.push(r)});
 assert.deepEqual([...ctx.root.querySelectorAll('[data-quran-route] b')].map(b=>b.textContent),['Ziyadah','Muroja’ah','Presensi Guru','Presensi Santri']);
 ctx.root.querySelectorAll('[data-quran-route]').forEach(b=>b.click());assert.deepEqual(visited,['quran-ziyadah','quran-murojaah','teacher-attendance','student-attendance']);
 await quranModule.namespace.renderTeacherQuran({...ctx,session:{...ctx.session,activeRole:'mentor_tahsin_tahfiz'}},'Murojaah');assert.equal($('#quranProgram'),null);assert.equal($('#murojaahField').hidden,false);
});
test('mixed-unit incident sends SD to its Wali Kelas and SMP to counselor atomically',async()=>{
 db={};const mixed={...ctx,master:{...ctx.master,students:[{id:'s1',name:'SD',unitId:'UNIT-SD'},{id:'s2',name:'SMP',unitId:'UNIT-SMP'}],classes:[{id:'c1',unitId:'UNIT-SD',homeroomStaffId:'wali'}]}};
 await routes['teacher-case'](mixed);ctx.root.querySelectorAll('[data-student]').forEach(c=>c.checked=true);$('#reportSource').value='langsung';$('#reportCategory').value='Kedisiplinan';$('#reportDescription').value='Kejadian lintas unit';await click('#sendReport');
 const sd=Object.values(read(`boarding/homeroom_cases/${ctx.yearId}`)),other=Object.values(read(`boarding/cases/${ctx.yearId}`));assert.equal(sd.length,1);assert.equal(sd[0].studentId,'s1');assert.equal(sd[0].assignedHomeroomStaffId,'wali');assert.equal(other.length,1);assert.equal(other[0].studentId,'s2');assert.equal(sd[0].groupId,other[0].groupId);
});

test('SD class teacher inbox handles own students and preserves legacy reports',async()=>{
 db={};const own={...ctx,master:{...ctx.master,students:[{id:'s1',name:'Anak Kelas Saya',unitId:'UNIT-SD'},{id:'s2',name:'Anak Kelas Lain',unitId:'UNIT-SD'}],classes:[{id:'c1',unitId:'UNIT-SD',homeroomStaffId:'staff1'},{id:'c2',unitId:'UNIT-SD',homeroomStaffId:'other'}],classAssignments:{s1:{classId:'c1'},s2:{classId:'c2'}}}};
 put(`boarding/homeroom_cases/${ctx.yearId}/own`,{studentId:'s1',status:'menunggu_wali_kelas',description:'Kejadian SD'});put(`boarding/homeroom_cases/${ctx.yearId}/other`,{studentId:'s2',status:'menunggu_wali_kelas'});put(`boarding/cases/${ctx.yearId}/legacy`,{studentId:'s1',status:'selesai',description:'Riwayat lama'});
 const module=await load(new URL('assets/js/homeroom-cases.js',base).href);await module.evaluate();await module.namespace.renderHomeroomCases(own);assert.match(ctx.root.textContent,/Riwayat lama/);assert.doesNotMatch(ctx.root.textContent,/Anak Kelas Lain/);$('[data-note="0"]').value='Sudah diklarifikasi dan dibina';$('[data-status="0"]').value='selesai';await click('[data-save="0"]');assert.equal(read(`boarding/homeroom_cases/${ctx.yearId}/own`).status,'selesai');assert.equal(Object.keys(read(`boarding/homeroom_cases/${ctx.yearId}/own`).homeroomHistory).length,1);assert.equal(read(`boarding/cases/${ctx.yearId}/legacy`).description,'Riwayat lama');
});

test('Arabic morning groups use GPS, group-only two-stage attendance, materials and Arabic grades',async()=>{
 db={};const gctx={...ctx,master:{...ctx.master,academicSchedules:[],groups:[{id:'arabic-test',name:'Kelompok Bahasa Arab Uji',programType:'arabic',mentorStaffId:'staff1',teachingEnabled:true,subjectId:'arabic',dailyScheduleId:'daily',unitId:'UNIT-PONDOK'}],subjects:[{id:'arabic',name:'Bahasa Arab Pagi'}],dailySchedules:[{id:'daily',academicYearId:ctx.yearId,day:now.day,startTime:'05:40',endTime:'06:10',programId:'program'}],groupAssignments:{'arabic-test':{s1:{status:'active'},s2:{status:'inactive'}}}}};
 const schedule=model.namespace.teacherSchedules(gctx)[0],key=model.namespace.assignmentKey(schedule);
 put('settings/teacherAttendance',{locations:{campus:{latitude:-8,longitude:116,radiusMeter:700}}});await home.namespace.openSchedule(gctx);await click(`[data-attend="${schedule.id}"]`);assert.equal(read(`academic/teaching_attendance/${ctx.yearId}/staff1/${now.date}/${schedule.id}`).groupId,'arabic-test');
 await routes['student-attendance'](gctx);await click('[data-schedule]');assert.equal(ctx.root.querySelectorAll('[data-student]').length,1);await click('#saveLearning');await click('#saveLearning');const saved=read(`academic/learning_sessions/${ctx.yearId}/staff1/${now.date}/${schedule.id}`);assert.equal(saved.stage,'FINAL');assert.equal(saved.groupId,'arabic-test');assert.equal(saved.classId,null);assert.deepEqual(Object.keys(saved.students),['s1']);
 await routes['lesson-plans'](gctx);assert.match($('#materialAssignment').textContent,/Kelompok Bahasa Arab Uji/);const input=$('[data-date]');input.value='Percakapan pagi';await click('#saveMaterials');const material=read(`academic/material_targets/${ctx.yearId}/staff1/${key}/semester_1/${input.dataset.date}`);assert.equal(material.groupId,'arabic-test');
 await routes.grades(gctx);await click('[data-schema="bahasa_arab"]');await click('[data-assignment]');await click('[data-type="bulanan"]');await click('[data-period]');for(const input of ctx.root.querySelectorAll('[data-component]'))input.value='80';await click('#saveDraft');const exam=Object.values(read(`academic/exam_sessions/${ctx.yearId}/staff1`))[0];assert.equal(exam.groupId,'arabic-test');assert.equal(exam.students.s1.score,80);assert.deepEqual(Object.keys(exam.students),['s1']);
});

test('final attendance success dialog appears only after save and returns to dashboard',async()=>{
 db={};let destination='';const c={...ctx,navigate:route=>destination=route};await routes['student-attendance'](c);await click('[data-schedule="j1"]');$('[data-student="s2"] input[value="Belum Hadir"]').checked=true;await click('#saveLearning');assert.equal($('.attendance-success'),null);await click('#saveLearning');assert.equal($('.attendance-success'),null);$('[data-student="s2"] input[value="Terlambat"]').checked=true;await click('#saveLearning');const dialog=$('.attendance-success');assert.ok(dialog.hasAttribute('open'));assert.match(dialog.textContent,/Presensi berhasil disimpan/);assert.equal(read(prefix).stage,'FINAL');await click('[data-attendance-home]');assert.equal(destination,'dashboard');assert.equal($('.attendance-success'),null);
});

test('GEMA stays visible in formal class without attendance controls and saves delegated marker through finalization',async()=>{
 db={};writes=[];
 const c={...ctx,master:{...ctx.master,students:ctx.master.students.map(s=>({...s,unitId:'UNIT-SMP'})),roomAssignments:{s1:{roomId:'ROOM-PTR-GEMA',status:'active',academicYearId:ctx.yearId}}}};
 await routes['student-attendance'](c);await click('[data-schedule]');
 assert.match($('[data-student="s1"]').textContent,/Presensi oleh Pembina GEMA/);
 assert.equal($('[data-student="s1"] input[type=radio]'),null);assert.ok($('[data-student="s2"] input[type=radio]'));
 await click('#allPresent');await click('#saveLearning');
 const path=writes.find(p=>p.includes('learning_sessions'));assert.ok(path);assert.equal(read(path).students.s1.status,null);assert.equal(read(path).students.s2.status,'Hadir');
 await click('#saveLearning');assert.equal(read(path).stage,'FINAL');assert.equal(read(path).students.s1.attendanceManagedBy,'GEMA');
});


test('teacher leave submits once, supervisor decides, and teacher sees the final status',async()=>{
 db={};writes=[];const module=await load(new URL('assets/js/teacher/leave.js',base).href);await module.evaluate();const render=module.namespace.renderTeacherLeave;
 await render(ctx);const form=$('#teacherLeaveForm');for(const [key,value] of Object.entries({unitId:'u1',type:'Sakit',startDate:now.date,endDate:now.date,startTime:'07:00',endTime:'12:00',reason:'Perlu istirahat',contact:'Kontak uji',handover:'Tugas latihan telah disiapkan'}))form.elements[key].value=value;form.elements.declaration.checked=true;
 await form.onsubmit({preventDefault(){}});const path=`academic/teacher_leaves/${ctx.yearId}/teacher`,requests=read(path);assert.equal(Object.keys(requests).length,1);const id=Object.keys(requests)[0];assert.equal(requests[id].teacherUid,'teacher');assert.ok(requests[id].lessons.length);assert.equal(read('academic/teaching_attendance'),null);
 await render({...ctx,session:{...ctx.session,user:{uid:'reviewer'},activeRole:'head_formal_school',profile:{name:'Kepala Sekolah',unitIds:['u1']}}});await click('[data-request]');$('#leaveDecisionNote').value='Penanganan kelas disetujui';await click('[data-decision="approved"]');assert.equal(read(path+'/'+id+'/decision').status,'approved');assert.equal(read(path+'/'+id+'/decision').actorUid,'reviewer');
 await render(ctx);assert.match(ctx.root.textContent,/Disetujui/);assert.equal($('[data-request]'),null);
});

test('parent permit reaches correct dorm head and decision appears to guardian',async()=>{
 db={};const mod=await load(new URL('assets/js/student-permits.js',base).href);await mod.evaluate();const render=mod.namespace.renderStudentPermits;
 const parent={...ctx,session:{user:{uid:'parent'},activeRole:'wali_santri',profile:{studentIds:['s1']}},master:{...ctx.master,rooms:[{id:'room',dormitoryId:'DORM-PUTRI'}],roomAssignments:{s1:{roomId:'room'}}}};
 await render(parent);const f=$('#studentPermitForm');assert.equal(f.elements.studentId.options.length,1);
 for(const [k,v] of Object.entries({studentId:'s1',type:'Kontrol / Medical Check Up',startDate:'2026-10-08T08:00',endDate:'2026-10-08T12:00',reason:'Kontrol',destination:'Klinik',pickup:'Ibu',relation:'Ibu',phone:'08000'}))f.elements[k].value=v;
 await f.onsubmit({preventDefault(){}});const p=`parent/permissions/${ctx.yearId}/s1`,id=Object.keys(read(p))[0];assert.equal(read(p+'/'+id).dormitoryId,'DORM-PUTRI');
 await render({...parent,session:{user:{uid:'head'},activeRole:'head_boys_dorm',profile:{}}});assert.equal($('[data-permit]'),null);
 await render({...parent,session:{user:{uid:'head'},activeRole:'head_girls_dorm',profile:{name:'Kepala Putri'}}});await click('[data-permit]');const review=$('.teacher-sheet form');review.elements.note.value='Dijemput ibu';await review.onsubmit({preventDefault(){},submitter:review.querySelector('[value=approved]')});assert.equal(read(p+'/'+id+'/decision').status,'approved');
 await render(parent);assert.match(ctx.root.textContent,/Disetujui/);assert.equal(read('academic/student_attendance'),null);
});
