/* Generated by CAHAYA White-Label Setup */
window.CAHAYA_CONFIG = {
  "version": "2026.08-white-label-v1",
  "app": {
    "name": "MADANI APP",
    "shortName": "MADANI",
    "workspaceName": "MADANI Workspace",
    "institutionName": "Pondok Pesantren Al-Madani Lombok",
    "institutionShortName": "Pondok Pesantren Al-Madani Lombok",
    "tagline": "Pusat Pembibitan Penghafal Al-Qur'an",
    "academicYear": "2026/2027",
    "domain": "madaniapp.online",
    "supportContact": "Admin Pesantren"
  },
  "branding": {
    "logo": "assets/logofi.png",
    "logoAlt": "Logo Pondok Pesantren Al-Madani Lombok",
    "favicon": "assets/logofi.png",
    "pwaIcon192": "assets/logofi.png",
    "pwaIcon512": "assets/logofi.png"
  },
  "theme": {
    "primary": "#669c35",
    "primaryDark": "#152347",
    "secondary": "#19c6e6",
    "accent": "#f2b63d",
    "success": "#29c58d",
    "danger": "#ff5f70"
  },
  "terminology": {
    "student": "Santri",
    "parent": "Wali Santri",
    "teacher": "Guru",
    "mentor": "Musyrif",
    "class": "Kelas",
    "room": "Kamar",
    "group": "Usrah"
  },
  "firebase": {
    "apiKey": "AIzaSyAjvA-ZrdLngCJmyOnCB7YY0P5sXjpIKhE",
    "authDomain": "madanilombok-f692d.firebaseapp.com",
    "databaseURL": "https://madanilombok-f692d-default-rtdb.firebaseio.com",
    "projectId": "madanilombok-f692d",
    "storageBucket": "madanilombok-f692d.firebasestorage.app",
    "messagingSenderId": "986196180038",
    "appId": "1:986196180038:web:678bccc61c4fd185ef1e47"
  },
  "modules": {
    "academic": true,
    "tahfiz": true,
    "nurturing": true,
    "counseling": true,
    "health": true,
    "permits": true,
    "finance": true,
    "cashier": true,
    "facilities": true,
    "observer": true,
    "assessment": true,
    "media": true,
    "chat": true,
    "pkl": true
  },
  "bandwidth": {
    "chatMessageLimit": 50,
    "feedLimit": 20,
    "reportDefaultDays": 31,
    "masterCacheHours": 24,
    "dashboardCacheMinutes": 5
  }
};
